# Generated by Django 2.0.2 on 2018-04-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180211_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='лайки'),
        ),
    ]
